# Generated by Django 3.2.9 on 2021-12-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211216_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='href',
            field=models.CharField(default='', max_length=64, verbose_name='href'),
            preserve_default=False,
        ),
    ]
