# Generated by Django 3.2.9 on 2021-12-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_productcategory_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='href',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(default='', verbose_name='href'),
            preserve_default=False,
        ),
    ]
